name: Moneygram scrape full search
run-name: Moneygram scrape full search
on:
  workflow_dispatch:
# workflow_call: would exceed depth limit

jobs:
  scrape:
    name: Scrape
    permissions:
      actions: write
    uses: ./.github/workflows/moneygram_chunks.yaml
    strategy:
      max-parallel: 1
      fail-fast: true
    with:
      payee_min: 100
      payee_max: 1000

  combine-data:
    permissions:
      actions: write
    name: Combine payee JSONs
    runs-on: ubuntu-latest
    needs: scrape

    steps:
    - name: Download partial JSONs
      uses: actions/download-artifact@v4
      with:
        pattern: mg-payee-chunk-*
        merge-multiple: true
        path: new-mg-chunks

    - name: Delete stale artifacts
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$REPO/actions/artifacts" --paginate | jq -s '.[].artifacts[] | select(.workflow_run.id | contains('"$RUN_ID"')) | select(.name | contains("mg-payee-chunk")) .id' > delete_artifacts.sh
        sed -i -e 's#^#gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/'"$REPO"'/actions/artifacts/#' delete_artifacts.sh
        source delete_artifacts.sh

    - name: Combine JSONs
      env:
        MIN: ${{ inputs.payee_min }}
        MAX: ${{ inputs.payee_max }}
      run: |
        ls -lsa new-mg-chunks
        cat new-mg-chunks/* | jq -s "add | unique | sort_by(.receiveCode | tonumber)" | tee mg-payees.json

    - name: Upload full JSON
      uses: actions/upload-artifact@v4
      with:
        name: mg-payees
        path: mg-payees.json
