name: Moneygram scrape range
run-name: Moneygram scrape range
on:
  workflow_dispatch:
    inputs:
      payee_min:
        required: true
        type: number
      payee_max:
        required: true
        type: number
  workflow_call:
    inputs:
      payee_min:
        required: true
        type: number
      payee_max:
        required: true
        type: number

jobs:
  setup:
    name: Set up matrix params
    runs-on: ubuntu-latest
    steps:
    - name: Create matrix parameters
      id: matrix-params
      env:
        MIN: ${{ inputs.payee_min }}
        MAX: ${{ inputs.payee_max }}
      run: |
        MAX="$((MAX - 1))"
        MATRIX_PARAMS="$(seq -s "," "$MIN" "$MAX")"
        MATRIX_PARAMS="{\"payee\": $(sed -e 's/,/}, {"payee": /g' <<< "$MATRIX_PARAMS")}"
        echo "matrix-params={\"include\": ["$MATRIX_PARAMS"]}" | tee $GITHUB_OUTPUT
    outputs:
      matrix-params: ${{ steps.matrix-params.outputs.matrix-params }}

  scrape-range:
    name: Scrape range
    uses: ./.github/workflows/moneygram_query.yaml
    needs: setup
    strategy:
      max-parallel: 25
      matrix: ${{ fromJson(needs.setup.outputs.matrix-params) }}
      fail-fast: true
    with:
      payee: ${{ matrix.payee }}

  combine-data:
    name: Combine payee JSONs
    permissions:
      actions: write
    runs-on: ubuntu-latest
    needs: scrape-range

    steps:
    - name: Download partial JSONs
      uses: actions/download-artifact@v4
      with:
        pattern: mg-payee-query-*
        merge-multiple: true
        path: new-mg-payees

    - name: Delete stale artifacts
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        GH_TOKEN: ${{ github.token }}
      run: |
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$REPO/actions/artifacts" --paginate | jq -s '.[].artifacts[] | select(.workflow_run.id | contains('"$RUN_ID"')) | select(.name | contains("mg-payee-query")) .id' > delete_artifacts.sh
        sed -i -e 's#^#gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/'"$REPO"'/actions/artifacts/#' delete_artifacts.sh
        source delete_artifacts.sh

    - name: Combine JSONs
      env:
        MIN: ${{ inputs.payee_min }}
        MAX: ${{ inputs.payee_max }}
      run: |
        ls -lsa new-mg-payees
        cat new-mg-payees/* | jq -s "add | unique | sort_by(.receiveCode | tonumber)" | tee mg-payee-range-$MIN-$MAX.json

    - name: Upload full JSON
      uses: actions/upload-artifact@v4
      with:
        name: mg-payee-range-${{ inputs.payee_min }}-${{ inputs.payee_max }}
        path: mg-payee-range-${{ inputs.payee_min }}-${{ inputs.payee_max }}.json
        retention-days: 1
